from __future__ import annotations

from typing import Protocol

from graphtask_r1.schema import EpisodeInput, Observation, StepResult, ToolCall


class ToolEnvironment(Protocol):
    def reset(self, sample: EpisodeInput, seed: int) -> Observation: ...
    def step(self, action: ToolCall) -> StepResult: ...
    def snapshot(self) -> dict[str, object]: ...
    def restore(self, state: dict[str, object]) -> None: ...
