name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          enable-cache: true
      - run: uv sync --all-extras
      - run: uv run make lint
      - run: uv run make typecheck
      - run: uv run make test

